version: '3'
services:
  mysql-container:
    image: mysql:8
    cap_add:
      - SYS_NICE
    environment:
      - TZ=Asia/shenzhen
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /Users/feng/coding/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: [
        'mysqld',
        # 设置字符编码
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
